profession = input ("Type a profession: ")
first_verb = input ("Type a verb: ")
famous_person = input ("Type a famous person name: ")
animal = input ("Type a type of animal: ")
unusual_profession = input ("Type an unusual profession: ")
place = input ("Type a place name: ")
name1 = input ("Type a name: ")
name2 = input ("Type a name: ")
name3 = input ("Type a name: ")
celeb_name = input ("Type a celeb name: ")
weapon = input ("Type a weapon: ")
adverb_ending_in_ly = input ("Type an adverb ending in ly: ")
meme = input ("Type a meme: ")

print (f"There once was a {profession} named Nakai.")
print (f"He really just waned to {first_verb}, but then {famous_person} came an turned him into a {animal}!")
print (f"No one knew, but it turns out that Nakai was really a {unusual_profession}.")
print (f"He lived in {place} and owned 3 animals named {name1}, {name2} and {name3}.")
print (f"One day on his way to town, he came across a horse named {celeb_name}.")
print (f"Little did he know, that the horse he came to know would later end his humanity... GEEBERS!")
print (f"How was he supposed to know that the horse would have been holding a {weapon}, who would have guessed?")
print (f"The horse then stabbed Nakai with the {weapon}, causing Nakai to scream {adverb_ending_in_ly}.")
print (f"Nakai fell to the ground, exausted.")
print (f"His last words were {meme}.")
